- name: Patch Windows Servers
  hosts: all
  connection: winrm
  gather_facts: yes
  become: no
  serial: "{{ batch_size | default(5) }}"
  any_errors_fatal: yes

  tasks:
    - name: check for updates
      win_updates:
        category_names: "{{ category_names | default(['CriticalUpdates', 'SecurityUpdates', 'UpdateRollups']) }}"
        state: searched
      register: update_check

    - name: perform patching procedures
      when: "update_check.found_update_count > 0"
      block:
        - name: set server to maintenance mode
          debug:
            msg: done

        - name: notify users
          win_msg:
            display_seconds: 60
            msg: "This system is being patched and may reboot shortly."

        - name: perform an update
          win_updates:
            category_names: "{{ category_names | default(['CriticalUpdates', 'SecurityUpdates', 'UpdateRollups']) }}"
            reboot: no
            state: installed
          register: update

        - debug:
            var: update

        - name: reboot the server if needed
          win_reboot:
          when: update.reboot_required
          register: reboot

        - name: save reboot time
          set_stats:
            per_host: yes
            data:
              reboot:
                rebooted: "{{ reboot.rebooted }}"
                elapsed: "{{ reboot.elapsed }}"
          when: update.reboot_required

        - name: perform health check
          debug:
            msg: pass

        - name: turn off maintenance mode
          debug:
            msg: done
